import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'qu';

const translations = {
  es: {
    // Navigation
    nav_home: 'Inicio',
    nav_candidates: 'Candidatos',
    nav_compare: 'Comparar Candidatos',
    nav_schedule: 'Cronograma Electoral',
    nav_about: 'Sobre nosotros',
    nav_authorities: 'Autoridades a elegir',
    nav_jnetv: 'JNE TV',
    nav_ai: 'Voto Informado con IA',
    nav_help: 'Ayuda',
    nav_menu: 'Menú',
    nav_open_menu: 'Abrir menú de navegación',
    nav_close_menu: 'Cerrar menú de navegación',

    // Accessibility toolbar
    acc_panel_title: 'Accesibilidad',
    acc_open: 'Abrir panel de accesibilidad',
    acc_close: 'Cerrar panel de accesibilidad',
    acc_text_size: 'Tamaño del texto',
    acc_small: 'Pequeño',
    acc_medium: 'Mediano',
    acc_large: 'Grande',
    acc_xlarge: 'Muy grande',
    acc_contrast: 'Alto contraste',
    acc_contrast_on: 'Activar alto contraste',
    acc_contrast_off: 'Desactivar alto contraste',
    acc_voice: 'Comandos de voz',
    acc_voice_on: 'Activar comandos de voz',
    acc_voice_off: 'Desactivar comandos de voz',
    acc_voice_listening: 'Escuchando…',
    acc_voice_say: 'Di: "inicio", "candidatos", "comparar", "cronograma"',
    acc_voice_heard: 'Escuché:',
    acc_voice_not_supported: 'Tu navegador no soporta comandos de voz',
    acc_language: 'Idioma / Simi',
    skip_to_content: 'Saltar al contenido principal',

    // Home page
    home_elections: 'ELECCIONES GENERALES',
    home_video_title: 'Exposición de',
    home_video_subtitle: 'Planes de Gobierno',
    home_video_desc: 'Videos de candidatos a la presidencia',
    home_presidents: 'Presidentes y vicepresidentes',
    home_deputies: 'Diputados',
    home_senators: 'Senadores',
    home_parliament: 'Parlamento Andino',
    home_revisa: '¿Revisa, compara y decide?',
    home_revisa_sub: 'Usa nuestra herramienta de Voto Informado con ElecciA',
    home_debate: 'DEBATE',
    home_debate_sub: 'Propuestas de candidatos',
    home_abroad: '¿Vives fuera del Perú?',
    home_abroad_sub: 'Infórmate cómo votar y quiénes son tus candidatos',
    home_first_vote: '¿Primera vez votando?',
    home_first_vote_sub: 'Te explicamos paso a paso cómo ejercer tu derecho al voto de forma informada',
    home_guide: 'Ver guía completa',
    home_3d_btn: 'ACCEDER A EXPERIENCIA 3D Y APRENDER A SUFRAGAR',
    home_3d_title: 'Simulador de Votación 3D',
    home_3d_desc: 'Ingresa a la experiencia interactiva 3D y aprende a votar correctamente en un local virtual.',
    home_coming_soon: 'Próximamente',
    home_coming_soon_sub: 'Esta sección estará disponible pronto. Estamos trabajando para brindarte la mejor información.',
    home_back: 'Volver al inicio',

    // Candidates page
    cand_title: 'Candidatos Presidenciales',
    cand_subtitle: 'Conoce y compara a los candidatos a la presidencia',
    cand_filter: 'Filtros',
    cand_filter_title: 'Filtrar candidatos',
    cand_filter_party: 'Partido Político',
    cand_filter_education: 'Nivel de estudios',
    cand_filter_experience: 'Experiencia Laboral',
    cand_filter_judicial: 'Antecedentes Judiciales',
    cand_filter_apply: 'Aplicar Filtros',
    cand_filter_clear: 'Limpiar Filtros',
    cand_filter_close: 'Cerrar filtros',
    cand_sort: 'Ordenar por:',
    cand_sort_name: 'Nombre',
    cand_sort_party: 'Partido',
    cand_compare_mode: 'Modo Comparación',
    cand_compare_exit: 'Salir',
    cand_compare_go: 'Comparar seleccionados',
    cand_compare_select: 'Selecciona 2 candidatos para comparar',
    cand_compare_selected: 'seleccionado(s)',
    cand_showing: 'Mostrando',
    cand_of: 'de',
    cand_results: 'candidatos',
    cand_see_more: 'Ver más candidatos',
    cand_see_less: 'Ver menos',
    cand_no_results: 'No se encontraron candidatos con los filtros seleccionados',
    cand_clear_filters: 'Limpiar filtros',
    cand_select_compare: 'Seleccionar para comparar',
    cand_deselect_compare: 'Deseleccionar',
    cand_view_profile: 'Ver perfil completo',
    cand_years: 'años',
    cand_no_penal: 'Sin sentencias penales',
    cand_no_nonpenal: 'Sin sentencias no penales',
    cand_has_nonpenal: 'Con sentencias no penales',
    cand_back: 'Volver a candidatos presidenciales',

    // Compare page
    comp_title: 'Comparar Candidatos',
    comp_subtitle: 'Selecciona hasta 2 candidatos para comparar',
    comp_back: 'Volver a candidatos presidenciales',
    comp_clear: 'Limpiar selección',
    comp_go: 'Comparar',
    comp_no_selection: 'Selecciona al menos 2 candidatos',

    // Schedule page
    sched_title: 'Cronograma Electoral 2026',
    sched_back: 'Volver al inicio',

    // Footer
    footer_contact: 'Contáctanos:',
    footer_rights: '© JNE. Todos los Derechos Reservados 2026',
    footer_follow: 'Síguenos en nuestras redes sociales:',

    // Candidate detail page
    detail_back: 'Volver a candidatos',
    detail_age: 'años',
    detail_party: 'Partido Político',
    detail_first_vp: 'Primer Vicepresidente',
    detail_second_vp: 'Segundo Vicepresidente',
    detail_education: 'Formación Académica',
    detail_experience: 'Experiencia Profesional',
    detail_proposals: 'Propuestas de Gobierno',
    detail_proposals_period: 'Plan de trabajo para el periodo 2026-2031',
    detail_compare_btn: 'Comparar con otros candidatos',
    detail_download: 'Descargar Plan de Gobierno completo',

    // Compare page
    comp_candidate_n: 'Candidato',
    comp_change: 'Cambiar',
    comp_select_prompt: 'Selecciona un candidato',
    comp_select_btn: 'Elegir candidato',
    comp_age: 'Edad:',
    comp_education_label: 'Educación:',
    comp_experience_label: 'Experiencia:',
    comp_judicial_label: 'Antecedentes:',
    comp_no_penal: 'Sin sentencias penales',
    comp_with_penal: 'Con sentencias penales',
    comp_no_nonpenal: 'Sin sentencias no penales',
    comp_with_nonpenal: 'Con sentencias no penales',
    comp_section_nav: 'Secciones',
    comp_proposals_title: 'Propuestas de Gobierno',
    comp_proposals_education: 'Educación',
    comp_proposals_health: 'Salud',
    comp_proposals_economy: 'Economía',
    comp_proposals_security: 'Seguridad',
    comp_proposals_environment: 'Medio Ambiente',
    comp_judicial_title: 'Antecedentes Judiciales',
    comp_penal_title: 'Sentencias Penales',
    comp_nonpenal_title: 'Sentencias No Penales',
    comp_none: 'Ninguna',
    comp_resume: 'Hoja de Vida',
    comp_gov_plan: 'Plan de Gobierno',
    comp_personal_info: 'INFORMACIÓN PERSONAL',
    comp_edu_header: 'EDUCACIÓN',
    comp_exp_header: 'EXPERIENCIA PROFESIONAL',
    comp_health_header: 'SALUD',
    comp_economy_header: 'ECONOMÍA',
    comp_security_header: 'SEGURIDAD',
    comp_env_header: 'MEDIO AMBIENTE',
    comp_resume_desc: 'Información personal, educación y experiencia profesional',
    comp_plan_desc: 'Propuestas en diferentes áreas de gestión pública',
    comp_age_label: 'Edad',
    comp_see_plan: 'Ver Plan de Gobierno',
    comp_back_resume: 'Volver a Hoja de Vida',
    comp_empty_title: 'Selecciona 2 candidatos para comparar',
    comp_empty_desc: 'Usa los botones "Cambiar" o "Elegir candidato" para seleccionar los candidatos',
    comp_modal_title: 'Cambiar Candidato',
    comp_modal_search: 'Buscar candidato...',
    comp_modal_party: 'Partido:',
    comp_modal_select: 'Elegir',

    // Cronograma page
    sched_title_full: 'Cronograma Electoral 2026',
    sched_subtitle: 'Calendario oficial del proceso electoral peruano',
    sched_legend: 'Leyenda',
    sched_completed: 'Completado',
    sched_upcoming: 'Próximo',
    sched_important: 'Importante',
    sched_pending: 'Pendiente',

    // Common
    back: 'Volver atrás',
    close: 'Cerrar',
    yes: 'Sí',
    no: 'No',
    loading: 'Cargando...',
    know_more: 'Conoce más',
    select: 'Seleccionar',
    university: 'Universitario',
    technical: 'Técnico',
    public_sector: 'Sector Público',
    private_sector: 'Sector Privado',
    both_sectors: 'Ambos Sectores',
  },
  qu: {
    // Navigation - Quechua (Southern Quechua / Runasimi)
    nav_home: 'Qallariy',
    nav_candidates: 'Akllakuqkuna',
    nav_compare: 'Akllakuqkunata Kikinchay',
    nav_schedule: 'Pacha Hapiy',
    nav_about: 'Ñuqanchikamanta',
    nav_authorities: 'Kamachiqkunata Akllay',
    nav_jnetv: 'JNE TV',
    nav_ai: 'Yachaywan Qillqay IA',
    nav_help: 'Yanapakuy',
    nav_menu: 'Menú',
    nav_open_menu: 'Puriy menúta pascay',
    nav_close_menu: 'Puriy menúta wichq\'ay',

    // Accessibility toolbar
    acc_panel_title: 'Tukuypaq',
    acc_open: 'Tukuypaq panelta pascay',
    acc_close: 'Tukuypaq panelta wichq\'ay',
    acc_text_size: 'Qillqa Hatun',
    acc_small: 'Uchuy',
    acc_medium: 'Chawpi',
    acc_large: 'Hatun',
    acc_xlarge: 'Hatunpuni',
    acc_contrast: 'Hatun Rijch\'aq',
    acc_contrast_on: 'Hatun rijch\'aqta ruway',
    acc_contrast_off: 'Hatun rijch\'aqta tukuchiy',
    acc_voice: 'Simiwan Kamay',
    acc_voice_on: 'Simiwan kamayta qallariy',
    acc_voice_off: 'Simiwan kamayta tukuchiy',
    acc_voice_listening: 'Uyarini…',
    acc_voice_say: 'Niy: "qallariy", "akllakuqkuna", "kikinchay", "pacha hapiy"',
    acc_voice_heard: 'Uyarini:',
    acc_voice_not_supported: 'Qhawaq masinki simiwan kamayta mana atinchu',
    acc_language: 'Idioma / Simi',
    skip_to_content: 'Allin runasimipi riy',

    // Home page
    home_elections: 'TUKUY LLAQTAQ AKLLAKUYNIN',
    home_video_title: 'Kamachiq Kaqkuna',
    home_video_subtitle: 'Llaqta Kamachiy',
    home_video_desc: 'Hatun kamachiq akllakuqkunap videonkuna',
    home_presidents: 'Hatun Kamachiqkuna',
    home_deputies: 'Llaqta Kamachiqkuna',
    home_senators: 'Hatun Rimaqkuna',
    home_parliament: 'Antasuyu Kamachiq Kuna',
    home_revisa: '¿Qhaway, kikinchay, akllay?',
    home_revisa_sub: 'Ñuqanchiq Yachaywan Qillqay kamachiyta llamk\'ay',
    home_debate: 'RIMANAKUY',
    home_debate_sub: 'Akllakuqkunap munayninkuna',
    home_abroad: '¿Perú Llaqtamantachu kanki?',
    home_abroad_sub: 'Imaynatas qillqanki, pitaq akllakuqniyki kasqanta yachakuy',
    home_first_vote: '¿Ñawpaq kutim qillqanki?',
    home_first_vote_sub: 'Imaynatas qillqanata ruwayta ruwayniykita yachachisunki',
    home_guide: 'Tukuy yachakuyta qhaway',
    home_3d_btn: '3D EXPERIENCIAMAN YAYKUY, AKLLAYTA YACHAKUYPAQ',
    home_3d_title: '3D Akllakuy Simulador',
    home_3d_desc: '3D simuladorman yaykuy hinallataq allinta akllayta yachakuy virtual yachaywasipi.',
    home_coming_soon: 'Huk p\'unchaypi',
    home_coming_soon_sub: 'Kay t\'aqapi aswan qhipaman tarikunqa. Allin willakuyta qoykiypaq llamk\'achkanchik.',
    home_back: 'Qallariman kutiy',

    // Candidates page
    cand_title: 'Hatun Kamachiq Akllakuqkuna',
    cand_subtitle: 'Hatun kamachiq akllakuqkunata reqsiy, kikinchay',
    cand_filter: 'Akllay',
    cand_filter_title: 'Akllakuqkunata akllay',
    cand_filter_party: 'Llaqta Kamachiy',
    cand_filter_education: 'Yachay Hatun',
    cand_filter_experience: 'Llamk\'ay Yachay',
    cand_filter_judicial: 'Huchayuq Kanankuna',
    cand_filter_apply: 'Aklayta Ruway',
    cand_filter_clear: 'Aklayta Chuyayay',
    cand_filter_close: 'Aklayta wichq\'ay',
    cand_sort: 'Allinchay:',
    cand_sort_name: 'Suti',
    cand_sort_party: 'Llaqta Kamachiy',
    cand_compare_mode: 'Kikinchay Ruway',
    cand_compare_exit: 'Lluqsiy',
    cand_compare_go: 'Akllasqakunata kikinchay',
    cand_compare_select: 'Kikinchaypi 2 akllakuqkunata akllay',
    cand_compare_selected: 'akllasqa(kuna)',
    cand_showing: 'Qhawachini',
    cand_of: '-manta',
    cand_results: 'akllakuqkuna',
    cand_see_more: 'Aswan akllakuqkunata qhaway',
    cand_see_less: 'Pisitawan qhaway',
    cand_no_results: 'Manam akllasqa filtrowanqa akllakuqkuna tarikurqanchu',
    cand_clear_filters: 'Aklayta chuyayay',
    cand_select_compare: 'Kikinchaypi akllay',
    cand_deselect_compare: 'Mana akllay',
    cand_view_profile: 'Tukuy willakuyta qhaway',
    cand_years: 'wata',
    cand_no_penal: 'Huchayuq mana kan',
    cand_no_nonpenal: 'Huk huchan mana kan',
    cand_has_nonpenal: 'Huk huchan kan',
    cand_back: 'Hatun kamachiq akllakuqkunaman kutiy',

    // Compare page
    comp_title: 'Akllakuqkunata Kikinchay',
    comp_subtitle: '2 akllakuqkunata akllay kikinchaypi',
    comp_back: 'Hatun kamachiq akllakuqkunaman kutiy',
    comp_clear: 'Akllasqata chuyayay',
    comp_go: 'Kikinchay',
    comp_no_selection: ' Iskay akllakuqkunata akllay',

    // Schedule page
    sched_title: 'Akllakuy Pacha Hapiy 2026',
    sched_back: 'Qallariman kutiy',

    // Footer
    footer_contact: 'Qayawayku:',
    footer_rights: '© JNE. Tukuy Atiyninkunan 2026',
    footer_follow: 'Llamk\'ay churanaykupi qatiwayku:',

    // Candidate detail page
    detail_back: 'Akllakuqkunaman kutiy',
    detail_age: 'wata',
    detail_party: 'Llaqta Kamachiy',
    detail_first_vp: 'Ñawpaq Ayudakuq Kamachiq',
    detail_second_vp: 'Iskay Ayudakuq Kamachiq',
    detail_education: 'Yachay',
    detail_experience: 'Llamk\'ay Yachay',
    detail_proposals: 'Kamachiy Munay',
    detail_proposals_period: 'Llamk\'ay ruway 2026-2031 pachapi',
    detail_compare_btn: 'Huk akllakuqkunawan kikinchay',
    detail_download: 'Tukuy kamachiy munayta urayman aysay',

    // Compare page
    comp_candidate_n: 'Akllakuq',
    comp_change: 'Tikray',
    comp_select_prompt: 'Akllakuqta akllay',
    comp_select_btn: 'Akllakuqta akllay',
    comp_age: 'Wata:',
    comp_education_label: 'Yachay:',
    comp_experience_label: 'Llamk\'ay:',
    comp_judicial_label: 'Huchankuna:',
    comp_no_penal: 'Huchayuq mana kan',
    comp_with_penal: 'Huchayuq kan',
    comp_no_nonpenal: 'Huk huchan mana kan',
    comp_with_nonpenal: 'Huk huchan kan',
    comp_section_nav: 'T\'aqakuna',
    comp_proposals_title: 'Kamachiy Munay',
    comp_proposals_education: 'Yachay',
    comp_proposals_health: 'Qhali Kay',
    comp_proposals_economy: 'Qullqi Ruway',
    comp_proposals_security: 'Llaqta Waqaychay',
    comp_proposals_environment: 'Allpa Mamanchis',
    comp_judicial_title: 'Huchankuna',
    comp_penal_title: 'Huchayuq Kanankuna',
    comp_nonpenal_title: 'Huk Huchankuna',
    comp_none: 'Mana ima',
    comp_resume: 'Llamk\'ay Kaq',
    comp_gov_plan: 'Kamachiy Ruway',
    comp_personal_info: 'RUNA WILLAKUY',
    comp_edu_header: 'YACHAY',
    comp_exp_header: 'LLAMK\'AY YACHAY',
    comp_health_header: 'QHALI KAY',
    comp_economy_header: 'QULLQI RUWAY',
    comp_security_header: 'LLAQTA WAQAYCHAY',
    comp_env_header: 'ALLPA MAMANCHIS',
    comp_resume_desc: 'Runa willakuy, yachay, hinallataq llamk\'ay yachay',
    comp_plan_desc: 'Kamachiy munayninkuna',
    comp_age_label: 'Wata',
    comp_see_plan: 'Kamachiy Ruwayta qhaway',
    comp_back_resume: 'Llamk\'ay Kaqman kutiy',
    comp_empty_title: 'Kikinchaypi 2 akllakuqkunata akllay',
    comp_empty_desc: '"Tikray" nispa akllakuqkunata akllay',
    comp_modal_title: 'Akllakuqta Tikray',
    comp_modal_search: 'Akllakuqta mask\'ay...',
    comp_modal_party: 'Llaqta Kamachiy:',
    comp_modal_select: 'Akllay',

    // Cronograma page
    sched_title_full: 'Akllakuy Pacha Hapiy 2026',
    sched_subtitle: 'Peru llaqtaq akllakuy pacha hapiy',
    sched_legend: 'Qhawarina',
    sched_completed: 'Tukusqa',
    sched_upcoming: 'Hamuq',
    sched_important: 'Allin',
    sched_pending: 'Suyanaq',

    // Common
    back: 'Qipaman kutiy',
    close: 'Wichq\'ay',
    yes: 'Ari',
    no: 'Mana',
    loading: 'Hamuchkani...',
    know_more: 'Aswan reqsiy',
    select: 'Akllay',
    university: 'Yachaqwasi',
    technical: 'Ruway Yachay',
    public_sector: 'Suyuq Llamk\'ay',
    private_sector: 'Apuq Llamk\'ay',
    both_sectors: 'Iskaynin Llamk\'ay',
  },
} as const;

export type TranslationKey = keyof typeof translations.es;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: TranslationKey): string => {
    return translations[language][key] ?? translations.es[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
